use_frameworks!

platform :ios, '9.0'

target 'SecureKit_Example' do
  pod 'SecureKit', :path => '../'

  target 'SecureKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
